name: bitcoin_tracking_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^6.0.0-nullsafety.1
  # Bloc for state management
  flutter_bloc: ^6.1.1
  # Value equality
  equatable: ^2.0.0-nullsafety.0
  # Functional programming thingies
  dartz: ^0.9.2
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.2
  # Local cache
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
